version: '3.8'
services:
  db:
    image: postgres:13
    container_name: booking_database
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - booking

  server:
    container_name: booking_server
    build: .
    entrypoint: ['./wait-for-it.sh', '${DB_HOSTNAME}:${DB_PORT}', '--', './entrypoint.sh']
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    networks:
      - booking

networks:
  booking:
    driver: bridge
