const RESERVATION_LIMIT = 10;
const ROOM_AVAILABILITY_HOURS = 8;
const BEGIN_OF_BUSINESS_DAY = 9;
const CLOSE_OF_BUSINESS_DAY = 17;

module.exports = {
  RESERVATION_LIMIT,
  ROOM_AVAILABILITY_HOURS,
  BEGIN_OF_BUSINESS_DAY,
  CLOSE_OF_BUSINESS_DAY,
};
